Тонкая настройка
htmlacademy-nodejs/1967311-typoteka-3 pull request #2
Opened 2021-12-19 18:31 UTC by tengri

2022-01-06 14:59 UTC, Krabaton requested changes

2022-01-06 14:59 UTC, Krabaton commented on src/service/cli/generate.js
> +    if (count > 1000) {
1000 вынести в константу и использовать по необходимости.

2022-01-06 14:59 UTC, Krabaton commented on src/service/cli/generate.js
> +    description: shuffle(SENTENCES).slice(1, 5).join(` `),
Почемe именно 5? В том смысле, что лучше осмысленно назвать константу и использовать ее дальше. Проще потом читать, что это такое.

2022-01-06 14:59 UTC, Krabaton commented on src/service/cli/generate.js
> +      exit(1)
Может process.exit?

2022-01-06 21:33 UTC, tengri commented on src/service/cli/generate.js
> +      exit(1)
Поправил. И настроил webstorm такое отлавливать

2022-01-06 21:33 UTC, tengri commented on src/service/cli/generate.js
> +    description: shuffle(SENTENCES).slice(1, 5).join(` `),
поправил

2022-01-06 21:33 UTC, tengri commented on src/service/cli/generate.js
> +    if (count > 1000) {
поправил

2022-01-07 18:12 UTC, tengri commented on src/service/cli/generate.js
> +    if (count > 1000) {
А ничего страшного что у меня 2 задачи в одном ПР?

2022-01-11 16:42 UTC, Krabaton commented on src/service/cli/generate.js
> +    if (count > 1000) {
Не важно

2022-01-11 16:42 UTC, merged