Module2 task2
htmlacademy-nodejs/1967311-typoteka-3 pull request #4
Opened 2022-01-07 20:05 UTC by tengri

2022-02-01 00:50 UTC, Krabaton requested changes

2022-02-01 00:50 UTC, Krabaton commented on src/service/cli/generate.js
> +    return content.trim().split(`\n`);
Мало операций. Мы пропускаем пустые строки. Мы пропускаем пустые символы вокруг сообщений. Надо чистить каждую строку и убирать пустые строки.

2022-02-01 00:50 UTC, Krabaton commented on src/service/cli/generate.js
> +const FILE_SENTENCES_PATH = `../../data/sentences.txt`;
Не должно быть относительных путей

2022-02-01 00:50 UTC, Krabaton commented on src/service/cli/generate.js
> +      const sentences = await readContent(FILE_SENTENCES_PATH);
На самом деле три await это не очень быстро, лучше их всех дождаться Promise.all

```js
const [sentences, titles, categories ] = await Promise.all([
  readContent(path.join(__dirname, FILE_SENTENCES_PATH)),
  readContent(path.join(__dirname, FILE_TITLES_PATH)),
  readContent(path.join(__dirname, FILE_CATEGORIES_PATH))
])
```

И убрать относительные пути. Собрать в абсолютный `path.join`  или `path.resolve`

2022-02-01 00:50 UTC, Krabaton commented on src/service/cli/generate.js
> +        await fs.writeFile(FILE_NAME, JSON.stringify(generateOffers(count, titles, categories, sentences)))
Тут явно напрашивается параметр, который объеденит `titles, categories, sentences`, чтобы в дальнейшем расширение параметров происходило безболезненно

2022-02-02 20:34 UTC, tengri commented on src/service/cli/generate.js
> +    return content.trim().split(`\n`);
Поправил

2022-02-02 20:35 UTC, tengri commented on src/service/cli/generate.js
> +const FILE_SENTENCES_PATH = `../../data/sentences.txt`;
Не совсем понял, если я буду хардкодить абсолютный путь, то это будет работать только на моей машине. Я использовал __dirname . Я правильно сделал?

2022-02-02 20:36 UTC, tengri commented on src/service/cli/generate.js
> +        await fs.writeFile(FILE_NAME, JSON.stringify(generateOffers(count, titles, categories, sentences)))
Поправил

2022-02-02 20:39 UTC, tengri commented on src/service/cli/generate.js
> +const FILE_SENTENCES_PATH = `../../data/sentences.txt`;
Заюзал path.join

2022-02-02 20:39 UTC, tengri commented on src/service/cli/generate.js
> +      const sentences = await readContent(FILE_SENTENCES_PATH);
сделал

2022-02-03 20:12 UTC, merged