module3-task2: Шаблонизируй это
htmlacademy-nodejs/1967311-typoteka-3 pull request #8
Opened 2022-02-15 14:50 UTC by tengri

2022-02-18 15:55 UTC, Krabaton requested changes

2022-02-18 15:55 UTC, Krabaton commented on src/express/routes/errors.js
> +errorsRouter.use((err, req, res) => {
Это не обработчик ошибок. По документации у обработчика должно быть 4 параметра. Здесь пропущен `next`

2022-02-18 15:55 UTC, Krabaton commented on src/express/routes/errors.js
> +errorsRouter.get(`*`, (req, res) => {
Неправильно. Мы должны на любой роут реагировать, а не только `get`. Используй `use`

2022-02-18 15:55 UTC, Krabaton commented on src/service/cli/generate.js
> +const fs = require(`fs`).promises;
`const fs = require('fs/promises');` Проще в тестах замокать.

2022-02-18 15:55 UTC, Krabaton commented on src/service/cli/generate.js
> +      return console.error(chalk.red(`Не больше 1000 постов`));
```js
console.error(chalk.red(`Не больше ${MAX_OFFER_COUNT} постов`))
```

2022-02-18 15:55 UTC, Krabaton commented on src/service/cli/generate.js
> +    return undefined;
Если возвращать то лучше всегда `null` ты подчеркиваешь этим осознанный возврат значения. `undefined` лучше оставить средствам языка.

2022-02-18 15:55 UTC, Krabaton commented on src/service/cli/server.js
> +const FILENAME = `../mocks.json`;
Если это имя файла то лучше оставить `const FILENAME = 'mocks.json'`;

А уже дальше сделать так

```js
const fileContent = await fs.readFile(path.join(__dirname, '..', FILENAME))
```

2022-02-19 16:15 UTC, tengri commented on src/express/routes/errors.js
> +errorsRouter.get(`*`, (req, res) => {
Не совсем понял, на post запрос, например, тоже надо отдавать красивую страницу? Я такого не припомню, обычно там ошибка простой строкой, о том, что нет ничего по этому пути

2022-02-19 16:20 UTC, tengri commented on src/service/cli/server.js
> +const FILENAME = `../mocks.json`;
eslint исправляет '' на ``. Исправить правило в линтере?
Сорри, что в первый раз за много ПР-ов запустил линтер)

2022-02-19 16:41 UTC, tengri commented on src/express/routes/errors.js
> +errorsRouter.use((err, req, res) => {
Не совсем понял, я нагуглил https://expressjs.com/en/guide/error-handling.html такое решение:
app.use((err, req, res, next) => {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
Но линтер ругается на наличие неиспользованного параметра next. Вот я его и убрал. Конечно обычно мидлвари должны встраиваться в цепочку обработчиков, а не возвращать респонс, но этот случай - исключение - мы ловим все ошибки и отдаем красивую страницу. Как нам использовать next в данном случае?

2022-02-19 16:42 UTC, tengri commented on src/service/cli/server.js
> +const FILENAME = `../mocks.json`;
исправил

2022-02-19 16:42 UTC, tengri commented on src/service/cli/generate.js
> +      return console.error(chalk.red(`Не больше 1000 постов`));
исправил

2022-02-19 16:43 UTC, tengri commented on src/service/cli/generate.js
> +    return undefined;
исправил

2022-02-19 19:24 UTC, Krabaton commented on src/express/routes/errors.js
> +errorsRouter.use((err, req, res) => {
Тогда
```js
errorsRouter.use((err, _req, res, _next) => {})
```

2022-02-19 19:25 UTC, Krabaton commented on src/express/routes/errors.js
> +errorsRouter.get(`*`, (req, res) => {
Ну елси формой отправляешь POST, то да красивую страницу рендеришь с ошибкой, что нет такого. Это просто ответ на любой не зарегистрированный роут не зависимо от метода.

2022-02-19 19:32 UTC, tengri commented on src/service/cli/generate.js
> +const fs = require(`fs`).promises;
исправил

2022-02-19 19:49 UTC, tengri commented on src/express/routes/errors.js
> +errorsRouter.use((err, req, res) => {
исправил

2022-02-20 15:07 UTC, merged